//
// CaptionSnippet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Basic details about a caption track, such as its language and name. */
public struct CaptionSnippet: Codable, Hashable {

    public enum AudioTrackType: String, Codable, CaseIterable {
        case unknown = "unknown"
        case primary = "primary"
        case commentary = "commentary"
        case descriptive = "descriptive"
    }
    public enum FailureReason: String, Codable, CaseIterable {
        case unknownformat = "unknownFormat"
        case unsupportedformat = "unsupportedFormat"
        case processingfailed = "processingFailed"
    }
    public enum Status: String, Codable, CaseIterable {
        case serving = "serving"
        case syncing = "syncing"
        case failed = "failed"
    }
    public enum TrackKind: String, Codable, CaseIterable {
        case standard = "standard"
        case asr = "ASR"
        case forced = "forced"
    }
    /** The type of audio track associated with the caption track. */
    public var audioTrackType: AudioTrackType?
    /** The reason that YouTube failed to process the caption track. This property is only present if the state property&#39;s value is failed. */
    public var failureReason: FailureReason?
    /** Indicates whether YouTube synchronized the caption track to the audio track in the video. The value will be true if a sync was explicitly requested when the caption track was uploaded. For example, when calling the captions.insert or captions.update methods, you can set the sync parameter to true to instruct YouTube to sync the uploaded track to the video. If the value is false, YouTube uses the time codes in the uploaded caption track to determine when to display captions. */
    public var isAutoSynced: Bool?
    /** Indicates whether the track contains closed captions for the deaf and hard of hearing. The default value is false. */
    public var isCC: Bool?
    /** Indicates whether the caption track is a draft. If the value is true, then the track is not publicly visible. The default value is false. @mutable youtube.captions.insert youtube.captions.update */
    public var isDraft: Bool?
    /** Indicates whether caption track is formatted for \&quot;easy reader,\&quot; meaning it is at a third-grade level for language learners. The default value is false. */
    public var isEasyReader: Bool?
    /** Indicates whether the caption track uses large text for the vision-impaired. The default value is false. */
    public var isLarge: Bool?
    /** The language of the caption track. The property value is a BCP-47 language tag. */
    public var language: String?
    /** The date and time when the caption track was last updated. */
    public var lastUpdated: Date?
    /** The name of the caption track. The name is intended to be visible to the user as an option during playback. */
    public var name: String?
    /** The caption track&#39;s status. */
    public var status: Status?
    /** The caption track&#39;s type. */
    public var trackKind: TrackKind?
    /** The ID that YouTube uses to uniquely identify the video associated with the caption track. @mutable youtube.captions.insert */
    public var videoId: String?

    public init(audioTrackType: AudioTrackType? = nil, failureReason: FailureReason? = nil, isAutoSynced: Bool? = nil, isCC: Bool? = nil, isDraft: Bool? = nil, isEasyReader: Bool? = nil, isLarge: Bool? = nil, language: String? = nil, lastUpdated: Date? = nil, name: String? = nil, status: Status? = nil, trackKind: TrackKind? = nil, videoId: String? = nil) {
        self.audioTrackType = audioTrackType
        self.failureReason = failureReason
        self.isAutoSynced = isAutoSynced
        self.isCC = isCC
        self.isDraft = isDraft
        self.isEasyReader = isEasyReader
        self.isLarge = isLarge
        self.language = language
        self.lastUpdated = lastUpdated
        self.name = name
        self.status = status
        self.trackKind = trackKind
        self.videoId = videoId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case audioTrackType
        case failureReason
        case isAutoSynced
        case isCC
        case isDraft
        case isEasyReader
        case isLarge
        case language
        case lastUpdated
        case name
        case status
        case trackKind
        case videoId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(audioTrackType, forKey: .audioTrackType)
        try container.encodeIfPresent(failureReason, forKey: .failureReason)
        try container.encodeIfPresent(isAutoSynced, forKey: .isAutoSynced)
        try container.encodeIfPresent(isCC, forKey: .isCC)
        try container.encodeIfPresent(isDraft, forKey: .isDraft)
        try container.encodeIfPresent(isEasyReader, forKey: .isEasyReader)
        try container.encodeIfPresent(isLarge, forKey: .isLarge)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(lastUpdated, forKey: .lastUpdated)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(trackKind, forKey: .trackKind)
        try container.encodeIfPresent(videoId, forKey: .videoId)
    }



}
