//
// ChannelLocalization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Channel localization setting */
public struct ChannelLocalization: Codable, Hashable {

    /** The localized strings for channel&#39;s description. */
    public var description: String?
    /** The localized strings for channel&#39;s title. */
    public var title: String?

    public init(description: String? = nil, title: String? = nil) {
        self.description = description
        self.title = title
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(title, forKey: .title)
    }



}
