//
// ChannelContentOwnerDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The contentOwnerDetails object encapsulates channel data that is relevant for YouTube Partners linked with the channel. */
public struct ChannelContentOwnerDetails: Codable, Hashable {

    /** The ID of the content owner linked to the channel. */
    public var contentOwner: String?
    /** The date and time when the channel was linked to the content owner. */
    public var timeLinked: Date?

    public init(contentOwner: String? = nil, timeLinked: Date? = nil) {
        self.contentOwner = contentOwner
        self.timeLinked = timeLinked
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentOwner
        case timeLinked
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(contentOwner, forKey: .contentOwner)
        try container.encodeIfPresent(timeLinked, forKey: .timeLinked)
    }



}
