//
// GeoPoint.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Geographical coordinates of a point, in WGS84. */
public struct GeoPoint: Codable, Hashable {

    /** Altitude above the reference ellipsoid, in meters. */
    public var altitude: Double?
    /** Latitude in degrees. */
    public var latitude: Double?
    /** Longitude in degrees. */
    public var longitude: Double?

    public init(altitude: Double? = nil, latitude: Double? = nil, longitude: Double? = nil) {
        self.altitude = altitude
        self.latitude = latitude
        self.longitude = longitude
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case altitude
        case latitude
        case longitude
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(altitude, forKey: .altitude)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(longitude, forKey: .longitude)
    }



}
