//
// LocalizedString.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct LocalizedString: Codable, Hashable {

    public var language: String?
    public var value: String?

    public init(language: String? = nil, value: String? = nil) {
        self.language = language
        self.value = value
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case language
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(value, forKey: .value)
    }



}
