//
// PropertyValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** A pair Property / Value. */
public struct PropertyValue: Codable, Hashable {

    /** A property. */
    public var property: String?
    /** The property&#39;s value. */
    public var value: String?

    public init(property: String? = nil, value: String? = nil) {
        self.property = property
        self.value = value
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case property
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(property, forKey: .property)
        try container.encodeIfPresent(value, forKey: .value)
    }



}
