//
// SuperChatEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** A &#x60;__superChatEvent__&#x60; resource represents a Super Chat purchase on a YouTube channel. */
public struct SuperChatEvent: Codable, Hashable {

    /** Etag of this resource. */
    public var etag: String?
    /** The ID that YouTube assigns to uniquely identify the Super Chat event. */
    public var id: String?
    /** Identifies what kind of resource this is. Value: the fixed string &#x60;\&quot;youtube#superChatEvent\&quot;&#x60;. */
    public var kind: String? = "youtube#superChatEvent"
    public var snippet: SuperChatEventSnippet?

    public init(etag: String? = nil, id: String? = nil, kind: String? = "youtube#superChatEvent", snippet: SuperChatEventSnippet? = nil) {
        self.etag = etag
        self.id = id
        self.kind = kind
        self.snippet = snippet
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case id
        case kind
        case snippet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(snippet, forKey: .snippet)
    }



}
