//
// VideoRecordingDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Recording information associated with the video. */
public struct VideoRecordingDetails: Codable, Hashable {

    public var location: GeoPoint?
    /** The text description of the location where the video was recorded. */
    public var locationDescription: String?
    /** The date and time when the video was recorded. */
    public var recordingDate: Date?

    public init(location: GeoPoint? = nil, locationDescription: String? = nil, recordingDate: Date? = nil) {
        self.location = location
        self.locationDescription = locationDescription
        self.recordingDate = recordingDate
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case location
        case locationDescription
        case recordingDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(locationDescription, forKey: .locationDescription)
        try container.encodeIfPresent(recordingDate, forKey: .recordingDate)
    }



}
