//
// VideoFileDetailsAudioStream.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Information about an audio stream. */
public struct VideoFileDetailsAudioStream: Codable, Hashable {

    /** The audio stream&#39;s bitrate, in bits per second. */
    public var bitrateBps: String?
    /** The number of audio channels that the stream contains. */
    public var channelCount: Int?
    /** The audio codec that the stream uses. */
    public var codec: String?
    /** A value that uniquely identifies a video vendor. Typically, the value is a four-letter vendor code. */
    public var vendor: String?

    public init(bitrateBps: String? = nil, channelCount: Int? = nil, codec: String? = nil, vendor: String? = nil) {
        self.bitrateBps = bitrateBps
        self.channelCount = channelCount
        self.codec = codec
        self.vendor = vendor
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bitrateBps
        case channelCount
        case codec
        case vendor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(bitrateBps, forKey: .bitrateBps)
        try container.encodeIfPresent(channelCount, forKey: .channelCount)
        try container.encodeIfPresent(codec, forKey: .codec)
        try container.encodeIfPresent(vendor, forKey: .vendor)
    }



}
