//
// ActivityContentDetailsSocial.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Details about a social network post. */
public struct ActivityContentDetailsSocial: Codable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case unspecified = "unspecified"
        case googleplus = "googlePlus"
        case facebook = "facebook"
        case twitter = "twitter"
    }
    /** The author of the social network post. */
    public var author: String?
    /** An image of the post&#39;s author. */
    public var imageUrl: String?
    /** The URL of the social network post. */
    public var referenceUrl: String?
    public var resourceId: ResourceId?
    /** The name of the social network. */
    public var type: ModelType?

    public init(author: String? = nil, imageUrl: String? = nil, referenceUrl: String? = nil, resourceId: ResourceId? = nil, type: ModelType? = nil) {
        self.author = author
        self.imageUrl = imageUrl
        self.referenceUrl = referenceUrl
        self.resourceId = resourceId
        self.type = type
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case author
        case imageUrl
        case referenceUrl
        case resourceId
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(author, forKey: .author)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(referenceUrl, forKey: .referenceUrl)
        try container.encodeIfPresent(resourceId, forKey: .resourceId)
        try container.encodeIfPresent(type, forKey: .type)
    }



}
