//
// ActivityContentDetailsPlaylistItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Information about a new playlist item. */
public struct ActivityContentDetailsPlaylistItem: Codable, Hashable {

    /** The value that YouTube uses to uniquely identify the playlist. */
    public var playlistId: String?
    /** ID of the item within the playlist. */
    public var playlistItemId: String?
    public var resourceId: ResourceId?

    public init(playlistId: String? = nil, playlistItemId: String? = nil, resourceId: ResourceId? = nil) {
        self.playlistId = playlistId
        self.playlistItemId = playlistItemId
        self.resourceId = resourceId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case playlistId
        case playlistItemId
        case resourceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(playlistId, forKey: .playlistId)
        try container.encodeIfPresent(playlistItemId, forKey: .playlistItemId)
        try container.encodeIfPresent(resourceId, forKey: .resourceId)
    }



}
