//
// ChannelTopicDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Freebase topic information related to the channel. */
public struct ChannelTopicDetails: Codable, Hashable {

    /** A list of Wikipedia URLs that describe the channel&#39;s content. */
    public var topicCategories: [String]?
    /** A list of Freebase topic IDs associated with the channel. You can retrieve information about each topic using the Freebase Topic API. */
    public var topicIds: [String]?

    public init(topicCategories: [String]? = nil, topicIds: [String]? = nil) {
        self.topicCategories = topicCategories
        self.topicIds = topicIds
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case topicCategories
        case topicIds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(topicCategories, forKey: .topicCategories)
        try container.encodeIfPresent(topicIds, forKey: .topicIds)
    }



}
