//
// ChannelConversionPings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The conversionPings object encapsulates information about conversion pings that need to be respected by the channel. */
public struct ChannelConversionPings: Codable, Hashable {

    /** Pings that the app shall fire (authenticated by biscotti cookie). Each ping has a context, in which the app must fire the ping, and a url identifying the ping. */
    public var pings: [ChannelConversionPing]?

    public init(pings: [ChannelConversionPing]? = nil) {
        self.pings = pings
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(pings, forKey: .pings)
    }



}
