//
// ChannelProfileDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct ChannelProfileDetails: Codable, Hashable {

    /** The YouTube channel ID. */
    public var channelId: String?
    /** The channel&#39;s URL. */
    public var channelUrl: String?
    /** The channel&#39;s display name. */
    public var displayName: String?
    /** The channels&#39;s avatar URL. */
    public var profileImageUrl: String?

    public init(channelId: String? = nil, channelUrl: String? = nil, displayName: String? = nil, profileImageUrl: String? = nil) {
        self.channelId = channelId
        self.channelUrl = channelUrl
        self.displayName = displayName
        self.profileImageUrl = profileImageUrl
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channelId
        case channelUrl
        case displayName
        case profileImageUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(channelId, forKey: .channelId)
        try container.encodeIfPresent(channelUrl, forKey: .channelUrl)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(profileImageUrl, forKey: .profileImageUrl)
    }



}
