//
// MembershipsLevelSnippet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct MembershipsLevelSnippet: Codable, Hashable {

    /** The id of the channel that&#39;s offering channel memberships. */
    public var creatorChannelId: String?
    public var levelDetails: LevelDetails?

    public init(creatorChannelId: String? = nil, levelDetails: LevelDetails? = nil) {
        self.creatorChannelId = creatorChannelId
        self.levelDetails = levelDetails
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case creatorChannelId
        case levelDetails
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(creatorChannelId, forKey: .creatorChannelId)
        try container.encodeIfPresent(levelDetails, forKey: .levelDetails)
    }



}
