//
// VideoMonetizationDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Details about monetization of a YouTube Video. */
public struct VideoMonetizationDetails: Codable, Hashable {

    public var access: AccessPolicy?

    public init(access: AccessPolicy? = nil) {
        self.access = access
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case access
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(access, forKey: .access)
    }



}
