//
// ActivityContentDetailsSubscription.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Information about a channel that a user subscribed to. */
public struct ActivityContentDetailsSubscription: Codable, Hashable {

    public var resourceId: ResourceId?

    public init(resourceId: ResourceId? = nil) {
        self.resourceId = resourceId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case resourceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(resourceId, forKey: .resourceId)
    }



}
