//
// ActivityContentDetailsRecommendation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Information that identifies the recommended resource. */
public struct ActivityContentDetailsRecommendation: Codable, Hashable {

    public enum Reason: String, Codable, CaseIterable {
        case reasonunspecified = "reasonUnspecified"
        case videofavorited = "videoFavorited"
        case videoliked = "videoLiked"
        case videowatched = "videoWatched"
    }
    /** The reason that the resource is recommended to the user. */
    public var reason: Reason?
    public var resourceId: ResourceId?
    public var seedResourceId: ResourceId?

    public init(reason: Reason? = nil, resourceId: ResourceId? = nil, seedResourceId: ResourceId? = nil) {
        self.reason = reason
        self.resourceId = resourceId
        self.seedResourceId = seedResourceId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason
        case resourceId
        case seedResourceId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(resourceId, forKey: .resourceId)
        try container.encodeIfPresent(seedResourceId, forKey: .seedResourceId)
    }



}
