//
// ChannelAuditDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** The auditDetails object encapsulates channel data that is relevant for YouTube Partners during the audit process. */
public struct ChannelAuditDetails: Codable, Hashable {

    /** Whether or not the channel respects the community guidelines. */
    public var communityGuidelinesGoodStanding: Bool?
    /** Whether or not the channel has any unresolved claims. */
    public var contentIdClaimsGoodStanding: Bool?
    /** Whether or not the channel has any copyright strikes. */
    public var copyrightStrikesGoodStanding: Bool?

    public init(communityGuidelinesGoodStanding: Bool? = nil, contentIdClaimsGoodStanding: Bool? = nil, copyrightStrikesGoodStanding: Bool? = nil) {
        self.communityGuidelinesGoodStanding = communityGuidelinesGoodStanding
        self.contentIdClaimsGoodStanding = contentIdClaimsGoodStanding
        self.copyrightStrikesGoodStanding = copyrightStrikesGoodStanding
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case communityGuidelinesGoodStanding
        case contentIdClaimsGoodStanding
        case copyrightStrikesGoodStanding
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(communityGuidelinesGoodStanding, forKey: .communityGuidelinesGoodStanding)
        try container.encodeIfPresent(contentIdClaimsGoodStanding, forKey: .contentIdClaimsGoodStanding)
        try container.encodeIfPresent(copyrightStrikesGoodStanding, forKey: .copyrightStrikesGoodStanding)
    }



}
