//
// ChannelBannerResource.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** A channel banner returned as the response to a channel_banner.insert call. */
public struct ChannelBannerResource: Codable, Hashable {

    public var etag: String?
    /** Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#channelBannerResource\&quot;. */
    public var kind: String? = "youtube#channelBannerResource"
    /** The URL of this banner image. */
    public var url: String?

    public init(etag: String? = nil, kind: String? = "youtube#channelBannerResource", url: String? = nil) {
        self.etag = etag
        self.kind = kind
        self.url = url
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case kind
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(url, forKey: .url)
    }



}
