//
// ChannelBrandingSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Branding properties of a YouTube channel. */
public struct ChannelBrandingSettings: Codable, Hashable {

    public var channel: ChannelSettings?
    /** Additional experimental branding properties. */
    public var hints: [PropertyValue]?
    public var image: ImageSettings?
    public var watch: WatchSettings?

    public init(channel: ChannelSettings? = nil, hints: [PropertyValue]? = nil, image: ImageSettings? = nil, watch: WatchSettings? = nil) {
        self.channel = channel
        self.hints = hints
        self.image = image
        self.watch = watch
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case channel
        case hints
        case image
        case watch
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(channel, forKey: .channel)
        try container.encodeIfPresent(hints, forKey: .hints)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(watch, forKey: .watch)
    }



}
