//
// ChannelStatistics.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Statistics about a channel: number of subscribers, number of videos in the channel, etc. */
public struct ChannelStatistics: Codable, Hashable {

    /** The number of comments for the channel. */
    public var commentCount: String?
    /** Whether or not the number of subscribers is shown for this user. */
    public var hiddenSubscriberCount: Bool?
    /** The number of subscribers that the channel has. */
    public var subscriberCount: String?
    /** The number of videos uploaded to the channel. */
    public var videoCount: String?
    /** The number of times the channel has been viewed. */
    public var viewCount: String?

    public init(commentCount: String? = nil, hiddenSubscriberCount: Bool? = nil, subscriberCount: String? = nil, videoCount: String? = nil, viewCount: String? = nil) {
        self.commentCount = commentCount
        self.hiddenSubscriberCount = hiddenSubscriberCount
        self.subscriberCount = subscriberCount
        self.videoCount = videoCount
        self.viewCount = viewCount
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case commentCount
        case hiddenSubscriberCount
        case subscriberCount
        case videoCount
        case viewCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(commentCount, forKey: .commentCount)
        try container.encodeIfPresent(hiddenSubscriberCount, forKey: .hiddenSubscriberCount)
        try container.encodeIfPresent(subscriberCount, forKey: .subscriberCount)
        try container.encodeIfPresent(videoCount, forKey: .videoCount)
        try container.encodeIfPresent(viewCount, forKey: .viewCount)
    }



}
