//
// Comment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** A *comment* represents a single YouTube comment. */
public struct Comment: Codable, Hashable {

    /** Etag of this resource. */
    public var etag: String?
    /** The ID that YouTube uses to uniquely identify the comment. */
    public var id: String?
    /** Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#comment\&quot;. */
    public var kind: String? = "youtube#comment"
    public var snippet: CommentSnippet?

    public init(etag: String? = nil, id: String? = nil, kind: String? = "youtube#comment", snippet: CommentSnippet? = nil) {
        self.etag = etag
        self.id = id
        self.kind = kind
        self.snippet = snippet
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case id
        case kind
        case snippet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(snippet, forKey: .snippet)
    }



}
