//
// I18nRegion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** A *i18nRegion* resource identifies a region where YouTube is available. */
public struct I18nRegion: Codable, Hashable {

    /** Etag of this resource. */
    public var etag: String?
    /** The ID that YouTube uses to uniquely identify the i18n region. */
    public var id: String?
    /** Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#i18nRegion\&quot;. */
    public var kind: String? = "youtube#i18nRegion"
    public var snippet: I18nRegionSnippet?

    public init(etag: String? = nil, id: String? = nil, kind: String? = "youtube#i18nRegion", snippet: I18nRegionSnippet? = nil) {
        self.etag = etag
        self.id = id
        self.kind = kind
        self.snippet = snippet
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case id
        case kind
        case snippet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(snippet, forKey: .snippet)
    }



}
