//
// LevelDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct LevelDetails: Codable, Hashable {

    /** The name that should be used when referring to this level. */
    public var displayName: String?

    public init(displayName: String? = nil) {
        self.displayName = displayName
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case displayName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(displayName, forKey: .displayName)
    }



}
