//
// LiveChatMessageRetractedDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct LiveChatMessageRetractedDetails: Codable, Hashable {

    public var retractedMessageId: String?

    public init(retractedMessageId: String? = nil) {
        self.retractedMessageId = retractedMessageId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case retractedMessageId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(retractedMessageId, forKey: .retractedMessageId)
    }



}
