//
// LiveStreamStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Brief description of the live stream status. */
public struct LiveStreamStatus: Codable, Hashable {

    public enum StreamStatus: String, Codable, CaseIterable {
        case created = "created"
        case ready = "ready"
        case active = "active"
        case inactive = "inactive"
        case error = "error"
    }
    public var healthStatus: LiveStreamHealthStatus?
    public var streamStatus: StreamStatus?

    public init(healthStatus: LiveStreamHealthStatus? = nil, streamStatus: StreamStatus? = nil) {
        self.healthStatus = healthStatus
        self.streamStatus = streamStatus
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case healthStatus
        case streamStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(healthStatus, forKey: .healthStatus)
        try container.encodeIfPresent(streamStatus, forKey: .streamStatus)
    }



}
