//
// Member.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** A *member* resource represents a member for a YouTube channel. A member provides recurring monetary support to a creator and receives special benefits. */
public struct Member: Codable, Hashable {

    /** Etag of this resource. */
    public var etag: String?
    /** Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#member\&quot;. */
    public var kind: String? = "youtube#member"
    public var snippet: MemberSnippet?

    public init(etag: String? = nil, kind: String? = "youtube#member", snippet: MemberSnippet? = nil) {
        self.etag = etag
        self.kind = kind
        self.snippet = snippet
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case kind
        case snippet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(snippet, forKey: .snippet)
    }



}
