//
// RelatedEntity.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct RelatedEntity: Codable, Hashable {

    public var entity: Entity?

    public init(entity: Entity? = nil) {
        self.entity = entity
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case entity
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(entity, forKey: .entity)
    }



}
