//
// SearchResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** A search result contains information about a YouTube video, channel, or playlist that matches the search parameters specified in an API request. While a search result points to a uniquely identifiable resource, like a video, it does not have its own persistent data. */
public struct SearchResult: Codable, Hashable {

    /** Etag of this resource. */
    public var etag: String?
    public var id: ResourceId?
    /** Identifies what kind of resource this is. Value: the fixed string \&quot;youtube#searchResult\&quot;. */
    public var kind: String? = "youtube#searchResult"
    public var snippet: SearchResultSnippet?

    public init(etag: String? = nil, id: ResourceId? = nil, kind: String? = "youtube#searchResult", snippet: SearchResultSnippet? = nil) {
        self.etag = etag
        self.id = id
        self.kind = kind
        self.snippet = snippet
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case id
        case kind
        case snippet
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(snippet, forKey: .snippet)
    }



}
