//
// ThumbnailDetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Internal representation of thumbnails for a YouTube resource. */
public struct ThumbnailDetails: Codable, Hashable {

    public var high: Thumbnail?
    public var maxres: Thumbnail?
    public var medium: Thumbnail?
    public var standard: Thumbnail?

    public init(high: Thumbnail? = nil, maxres: Thumbnail? = nil, medium: Thumbnail? = nil, standard: Thumbnail? = nil) {
        self.high = high
        self.maxres = maxres
        self.medium = medium
        self.standard = standard
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case high
        case maxres
        case medium
        case standard
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(high, forKey: .high)
        try container.encodeIfPresent(maxres, forKey: .maxres)
        try container.encodeIfPresent(medium, forKey: .medium)
        try container.encodeIfPresent(standard, forKey: .standard)
    }



}
