//
// VideoAbuseReportReasonListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

public struct VideoAbuseReportReasonListResponse: Codable, Hashable {

    /** Etag of this resource. */
    public var etag: String?
    /** Serialized EventId of the request which produced this response. */
    public var eventId: String?
    /** A list of valid abuse reasons that are used with &#x60;video.ReportAbuse&#x60;. */
    public var items: [VideoAbuseReportReason]?
    /** Identifies what kind of resource this is. Value: the fixed string &#x60;\&quot;youtube#videoAbuseReportReasonListResponse\&quot;&#x60;. */
    public var kind: String? = "youtube#videoAbuseReportReasonListResponse"
    /** The &#x60;visitorId&#x60; identifies the visitor. */
    public var visitorId: String?

    public init(etag: String? = nil, eventId: String? = nil, items: [VideoAbuseReportReason]? = nil, kind: String? = "youtube#videoAbuseReportReasonListResponse", visitorId: String? = nil) {
        self.etag = etag
        self.eventId = eventId
        self.items = items
        self.kind = kind
        self.visitorId = visitorId
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case etag
        case eventId
        case items
        case kind
        case visitorId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(etag, forKey: .etag)
        try container.encodeIfPresent(eventId, forKey: .eventId)
        try container.encodeIfPresent(items, forKey: .items)
        try container.encodeIfPresent(kind, forKey: .kind)
        try container.encodeIfPresent(visitorId, forKey: .visitorId)
    }



}
