//
// WatchSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import AnyCodable

/** Branding properties for the watch. All deprecated. */
public struct WatchSettings: Codable, Hashable {

    /** The text color for the video watch page&#39;s branded area. */
    public var backgroundColor: String?
    /** An ID that uniquely identifies a playlist that displays next to the video player. */
    public var featuredPlaylistId: String?
    /** The background color for the video watch page&#39;s branded area. */
    public var textColor: String?

    public init(backgroundColor: String? = nil, featuredPlaylistId: String? = nil, textColor: String? = nil) {
        self.backgroundColor = backgroundColor
        self.featuredPlaylistId = featuredPlaylistId
        self.textColor = textColor
    }
    public enum CodingKeys: String, CodingKey, CaseIterable {
        case backgroundColor
        case featuredPlaylistId
        case textColor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(backgroundColor, forKey: .backgroundColor)
        try container.encodeIfPresent(featuredPlaylistId, forKey: .featuredPlaylistId)
        try container.encodeIfPresent(textColor, forKey: .textColor)
    }



}
